language: python
python: '2.7'

branches:
  only:
  - master

before_install:
- git clone https://github.com/yuex/pelican-chameleon ~/pelican-chameleon
- git clone https://github.com/ingwinlu/pelican-bootstrapify ~/pelican-bootstrapify
- git clone https://github.com/LukasWoodtli/LukasWoodtli.github.io ~/github-userpage

install:
- pip install pelican
- pip install Markdown
- pip install typogrify
- pip install BeautifulSoup4
- pip install ghp-import

before_script:
- pelican-themes -i ~/pelican-chameleon
- git config --global user.name GIT_NAME
- git config --global user.email GIT_EMAIL

script:
- cd pelican
- make html

- cp -r ./output ~/github-userpage/
- cd  ~/github-userpage/
- git add *
- git commit -m"Travis CI"
- git push --force --quiet "https://${GH_TOKEN}@github.com/LukasWoodtli/LukasWoodtli.github.io" master



env:
  global:
    secure: JNdLq0N//T+PC2ms1PUGT04Udj49VzQhlGORVrjQA2VeJmBEahpBfU7IGYN6sIsvlJqeg0acDxQqb/RIZetifoJAf9Vtf5+BvNEh5M7aRTf1Sw5ECizyeuVOq04eI/sJvsTn5Q3AfmGUchMCrvqE78r5UoEd5aLP8bijYF99Rqo=
