language: python
python: '2.7'

branches:
  only:
  - master

before_install:
- pip install --upgrade pip

install:
  # Pelican for generating the web page
- pip install pelican
  # Markdown for writing content on the page
- pip install Markdown
- pip install typogrify
  # bs4 is used by pelican-bootstrapify plug in
- pip install BeautifulSoup4
  # gitpython used for build file
- pip install gitpython
  # needed for linkchecker
- pip install requests==2.2.0
  # check for broken links
- pip install linkchecker
  # highlighting of inline code in rst
- pip install sphinxcontrib-inlinesyntaxhighlight

before_script:
- git config --global user.name "travis (Lukas Woodtli)"
- git config --global user.email lukas_woodtli@travis.example.com

script:
- python generate_page.py
# it's not working??? - linkchecker http://lukaswoodtli.github.io

env:
  matrix:
    secure: QiCjd/QdpGf2xaGOH4odghvahFi+/FkmjE3WbszItmkD1fswH3iG/L0x1VP5BtGsxEEiWzR/tAVJPaqUdyhmfqttfhVKfyyuUz4d09DcehmhenjLL6pHOUVm6QyxWNkMIuEaYdZ3zzwFndQTsnccZsNvbxByPABwqlQ8lJm+e3s=
