language: python
python: "2.7"

branches:
  only:
  - master

before_install:
- git clone https://github.com/yuex/pelican-chameleon ~/pelican-chameleon
- git clone https://github.com/ingwinlu/pelican-bootstrapify ~/pelican-bootstrapify


install:
- pip install pelican
- pip install Markdown
- pip install typogrify
- pip install BeautifulSoup4
- pip install ghp-import

before_script:
- pelican-themes -i ~/pelican-chameleon

script:
- cd pelican
- make html

