language: python
python: '2.7'

branches:
  only:
  - master

install:
  # Pelican for generating the web page
- pip install pelican
  # Markdown for writing content on the page
- pip install Markdown
- pip install typogrify
  # bs4 is used by pelican-bootstrapify plug in
- pip install BeautifulSoup4
  # gitpython used for build file
- pip install gitpython

before_script:
- git config --global user.name ${GIT_NAME}
- git config --global user.email ${GIT_EMAIL}

script:
- python generate_page.py

env:
  global:
    secure: JNdLq0N//T+PC2ms1PUGT04Udj49VzQhlGORVrjQA2VeJmBEahpBfU7IGYN6sIsvlJqeg0acDxQqb/RIZetifoJAf9Vtf5+BvNEh5M7aRTf1Sw5ECizyeuVOq04eI/sJvsTn5Q3AfmGUchMCrvqE78r5UoEd5aLP8bijYF99Rqo=

