language: python
python: "2.7"

branches:
  only:
  - master

before_install:
- git clone https://github.com/yuex/pelican-chameleon ~/pelican-chameleon

install:
- pip install pelican
- pip install Markdown
- pip install typogrify

before_script:
- pelican-themes -i ~/pelican-chameleon

script:
- de pelican
- make html


